# Lattice Boltzmann sample, written in Java
#
# Main author: Jean-Luc Falcone
# Co-author: Jonas Latt
# Copyright (C) 2006 University of Geneva
# Address: Jean-Luc Falcone, Rue General Dufour 24,
#          1211 Geneva 4, Switzerland 
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public 
# License along with this program; if not, write to the Free 
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.


# Run the program using the following command:
# java lb/Unsteady

Unsteady:
	javac -source 5 -classpath $(PWD) lb/Unsteady.java 

clean:
	/bin/rm -f `find . -name "*.class"`
	/bin/rm -f `find . -name "*~"`
